"""
generation/answer.py

Grounded generation using Groq llama-3.3-70b-versatile.

Retrieves the top 5 chunks from ChromaDB, builds a numbered context block,
and instructs the LLM to answer only from that context. Source attribution
is built programmatically from chunk metadata — not generated by the LLM.

Usage:
    python generation/answer.py
    python generation/answer.py "your question here"
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from groq import Groq
from sentence_transformers import SentenceTransformer

# Allow imports from retrieval/ when running this file directly
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from retrieval.search import get_collection, retrieve

load_dotenv()

GROQ_MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """\
You are a helpful assistant for Liberty University students researching off-campus housing.

Answer using ONLY the retrieved context provided below. Do not use outside knowledge.
Cite sources inline using labels like [Source 1], [Source 2], etc. that match the numbered
sources in the context. Cite every source that supports a claim.

If the retrieved context does not contain enough information to answer the question, respond
with exactly:
    I do not have enough information in the provided sources to answer that.

Do not speculate, infer, or add any information not present in the context.\
"""

# Questions used for CLI testing — mirrors the Evaluation Plan in planning.md
TEST_QUESTIONS = [
    "I am a freshman at Liberty University and want to move off campus next spring. Am I automatically eligible to live off campus?",
    "I want to live off campus but I do not have a car. What transportation options could help me get to campus?",
    "What does The Oasis offer for Liberty students, and how much does it cost per bedroom?",
    "What do student discussions say about living at The Oasis as a graduate student or older student?",
    "What meal plan should I get as a freshman?",  # not in sources — should trigger fallback
]


# ---------------------------------------------------------------------------
# Context building
# ---------------------------------------------------------------------------

def build_context(chunks: list[dict]) -> str:
    """Format retrieved chunks into a numbered context block for the prompt."""
    parts = []
    for i, chunk in enumerate(chunks, start=1):
        m = chunk["meta"]
        parts.append(
            f"[Source {i}]\n"
            f"Title: {m['title']}\n"
            f"Source Type: {m['source_type']}\n"
            f"Source: {m['source']}\n"
            f"Content:\n{chunk['text']}"
        )
    return "\n\n---\n\n".join(parts)


# ---------------------------------------------------------------------------
# Source attribution
# ---------------------------------------------------------------------------

def build_sources(chunks: list[dict]) -> list[dict]:
    """
    Build a deduplicated source list from the retrieved chunks.

    Chunks from the same file are grouped into a single source entry.
    The lowest [Source N] label for that file is kept so it matches
    what the LLM cited in the answer.
    """
    seen: dict[str, dict] = {}
    sources: list[dict] = []

    for i, chunk in enumerate(chunks, start=1):
        m = chunk["meta"]
        key = m["filename"]
        if key not in seen:
            entry = {
                "label": f"Source {i}",
                "title": m["title"],
                "source_type": m["source_type"],
                "source": m["source"],
                "filename": m["filename"],
                "chunk_numbers": [int(m["chunk_number"])],
            }
            seen[key] = entry
            sources.append(entry)
        else:
            seen[key]["chunk_numbers"].append(int(m["chunk_number"]))

    return sources


# ---------------------------------------------------------------------------
# Main generation function
# ---------------------------------------------------------------------------

def answer(
    question: str,
    collection,
    model: SentenceTransformer,
    groq_client: Groq,
) -> tuple[str, list[dict]]:
    """
    Retrieve context, call Groq, and return (answer_text, sources).

    sources is a list of dicts with keys:
        label, title, source_type, source, filename, chunk_numbers
    """
    chunks = retrieve(question, collection, model)
    context = build_context(chunks)

    response = groq_client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"Retrieved context:\n\n{context}\n\nQuestion: {question}",
            },
        ],
        temperature=0.1,  # low temperature keeps answers factual and grounded
    )

    answer_text = response.choices[0].message.content.strip()
    sources = build_sources(chunks)
    return answer_text, sources


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def _print_result(question: str, answer_text: str, sources: list[dict]) -> None:
    print(f"\n{'=' * 70}")
    print(f"QUESTION: {question}")
    print(f"{'=' * 70}")
    print(f"\nANSWER:\n{answer_text}")
    print("\nSOURCES:")
    for s in sources:
        chunks_str = ", ".join(str(n) for n in s["chunk_numbers"])
        print(f"  [{s['label']}] {s['title']} ({s['source_type']})")
        print(f"           {s['source']}")
        print(f"           {s['filename']} — chunk(s) {chunks_str}")
    print(f"{'-' * 70}")


def main() -> None:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        sys.exit("ERROR: GROQ_API_KEY not set. Add it to your .env file.")

    collection  = get_collection()
    model       = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    groq_client = Groq(api_key=api_key)

    questions = [" ".join(sys.argv[1:])] if len(sys.argv) > 1 else TEST_QUESTIONS

    for q in questions:
        ans, sources = answer(q, collection, model, groq_client)
        _print_result(q, ans, sources)


if __name__ == "__main__":
    main()
